-- IN-PLACE EDIT (SCA-282, correctness-blocks-fresh-init exception per
-- CLAUDE.md §Schema truth):
--   This file was originally named `20260508000008_drop_deletion_requests_completed_at.sql`
--   and shared the `20260508000008` version prefix with
--   `20260508000008_deletion_request_sla_alerts.sql`. Same fresh-init
--   PK collision as SCA-282's 000006/000007 fixes. `_deletion_request_sla_alerts`
--   keeps the canonical timestamp (it's part of the SCA-88 deletion-
--   fulfillment lineage referenced by the SCA-268 README discussion);
--   `_drop_deletion_requests_completed_at` rebases to `_000081_...`.
--
--   Note: README.md previously claimed the three collision pairs
--   (000006/000007/000008) were safe-to-leave because their bodies
--   were commutative. That reasoning was empirically wrong — the PK
--   collision fires in `schema_migrations` regardless of body
--   commutativity. README updated alongside this rename.
--
-- SCA-230 — drop unused deletion_requests.completed_at column.
--
-- Pre-flight (2026-05-08): grep across Backend/supabase/ confirmed
-- the only references to `completed_at` within deletion_requests
-- context are the column declaration itself (migration
-- 20260508000002 line 42) plus in-memory references inside
-- external_refs_json SubsystemRecord shapes — those are JSONB
-- payload fields, NOT the column.
--
-- ADR 0031 explicitly states that successful deletions persist as
-- audit_log rows, not deletion_requests rows (the cascade wipes
-- deletion_requests when app_users is deleted). The `completed_at`
-- column was a vestige of an earlier design where success state was
-- supposed to land on the deletion_requests row itself; that design
-- was superseded by the audit_log anchor pattern. The column is
-- dead in the current code.
--
-- Forward migration (immutable-migration policy: never edit the
-- original).

ALTER TABLE deletion_requests DROP COLUMN IF EXISTS completed_at;
